const GET_IMAGES = 'GET_IMAGES';
const GET_IMAGES_FAILURE = 'GET_IMAGES_FAILURE';
const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
const SET_SEARCH_BAR = 'SET_SEARCH_BAR';
const SELECTED_PHOTO = 'SELECTED_PHOTO';
const DELETE_PHOTO = 'DELETE_PHOTO';
const DELETE_PHOTO_FAILURE = 'DELETE_PHOTO_FAILURE';
const DELETE_PHOTO_SUCCESS = 'DELETE_PHOTO_SUCCESS';

export {
  GET_IMAGES,
  GET_IMAGES_SUCCESS,
  GET_IMAGES_FAILURE,
  SET_SEARCH_BAR,
  SELECTED_PHOTO,
  DELETE_PHOTO,
  DELETE_PHOTO_FAILURE,
  DELETE_PHOTO_SUCCESS
}
