const GET_IMAGES = 'GET_IMAGES';
const GET_IMAGES_FAILURE = 'GET_IMAGES_FAILURE';
const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
const SET_SEARCH_BAR = 'SET_SEARCH_BAR';

export {
  GET_IMAGES,
  GET_IMAGES_SUCCESS,
  GET_IMAGES_FAILURE,
  SET_SEARCH_BAR
}
